### ISSUE TITLE
Add ability to specify category

### ISSUE THREAD

**Issue by RockinChaos** [fastticketbot/FastTicket#146]
Not sure if this is already a feature--I can't seem to find it anywhere.

I would love to ability to specify a category that the newly opened tickets get placed under. I have a category defined as `Support` where there is a channel to create tickets but the tickets get put at the top of the discord (outside of any categories). I would love a command such as;
`-value category <category>`

Thanks for creating such a fantastic bot!

**Comment by CoffeeMakesSense** [comment]
This would be an amazing feature! I agree there should be a way to specify a category.

EDIT: I would try emailing the dev, due to not really any of these requests being fulfilled. The one he has listed on the fastticketbot page is "kavin@kavin.rocks"

**Comment by FireMasterK** [comment]
Let me know if there are any bugs in the current implementation.
