### ISSUE TITLE
[Bug] Open ticket tag

### ISSUE THREAD

**Issue by Neresh** [fastticketbot/FastTicket#17]
Hi,

There's a bug with this function, in fact if I turn it to true and add a role (which can see the ticket), the bot won't tag the person who opened the ticket :/

Mb it's my fault due to a wrong discord setting ?

**Comment by FireMasterK** [comment]
Hi,
The role feature is to tag a specific role on ticket open and ping them eg: A support role,
currently, the bot only tags the staff, I will add a feature for you to ping the opener.

**Comment by FireMasterK** [comment]
Hi,
I've made some changes to the bot today,
try running the command `-value ping_opener true`
That should get what you are looking for 😃
