### ISSUE TITLE
Too Many Servers

### ISSUE THREAD

**Issue by Navigations** [fastticketbot/FastTicket#186]
The bot is in too many servers and it is unverified so I cannot add it to my server. Is there anything you can do? I provided a screenshot of the error.

https://imgur.com/a/HBXZ01Z

**Comment by FireMasterK** [comment]
Due to discord's new change for discord bots: https://support.discord.com/hc/en-us/community/posts/360061029252-Remove-ID-verification-for-Bots, I don't trust discord with my real-life ID.

So, consider self-hosting the bot, or use a different bot which has been verified.
