### ISSUE TITLE
[Suggestions] : Force reason & React to close

### ISSUE THREAD

**Issue by ghost** [fastticketbot/FastTicket#21]
Loving this ticket system!  Very  easy to use without a problem. 2 suggestions I was thinking was, option to force users to put a reason and secondly when the ticket channel is created, the ability to press a reaction to close the ticket after set time.

**Comment by FireMasterK** [comment]
Hi there!
Glad you're enjoying the system!
I will implement both of these in a few days
- Emoji Ticket Close
- Required ticket reason configuration option for -new command

Thanks

**Comment by FireMasterK** [comment]
- Required ticket reason configuration option for -new command

has been completed

Run the command `-value force_reason true` to enable the feature.

**Comment by FireMasterK** [comment]
This should be complete, let me know if there are any issues in the current implementation. 😃

**Comment by ghost** [comment]
Works well! Thanks, only issue is that the bot should put the question they asked in the ticket chat.

**Comment by FireMasterK** [comment]
Hi there,
that is already possible by using the placeholder `%reason%` in the `Ticket Open Reason` configuration value.
