### ISSUE TITLE
[Suggestion] Add a command to rename tickets?

### ISSUE THREAD

**Issue by Navigations** [fastticketbot/FastTicket#30]
Adding the possibility to rename tickets will allow Ticket Support Staff to sort through tickets etc. Add a command such as -rename <ticketName>

Example: -rename admin-support-ticket

**Comment by FireMasterK** [comment]
Sure,
I'll add this feature soon.

**Comment by Navigations** [comment]
Sounds good :)

**Comment by FireMasterK** [comment]
Feature completed, let me know if you find any bugs.

**Comment by Navigations** [comment]
Wow that was fast! I've given it a test and it works exactly how I pictured! Thank you so much :)
